---
title: "Penguins"
author: "Colin Quirk"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup}
library(tidyverse)
library(palmerpenguins)

theme_set(theme_minimal())

set.seed(1)
```


```{r}
penguins = penguins %>% 
  filter(!is.na(bill_length_mm), !is.na(sex))

head(penguins)
```

```{r}
mean(is.na(penguins$body_mass_g))
```


```{r}
count(penguins, species, island)
```

```{r}
ggplot(penguins, aes(x = bill_length_mm, fill = species)) +
  geom_histogram(position='identity', alpha=0.5)
```

```{r}
ggplot(penguins, aes(x = bill_depth_mm, fill = species)) +
  geom_histogram(position='identity', alpha=0.5)
```

```{r}
ggplot(penguins, aes(x = flipper_length_mm, fill = species)) +
  geom_histogram(position='identity', alpha=0.5)
```

```{r}
ggplot(penguins, aes(x = body_mass_g, fill = species)) +
  geom_histogram(position='identity', alpha=0.5)
```

```{r}
ggplot(penguins, aes(x = bill_length_mm, y=bill_depth_mm, color = species)) +
  geom_point()
```

```{r}
penguins_by_sex = penguins %>% 
  filter(!is.na(sex)) %>% 
  group_by(species, sex) %>% 
  summarise(bill_depth_mm = mean(bill_depth_mm),
            bill_length_mm = mean(bill_length_mm),
            flipper_length_mm = mean(flipper_length_mm),
            body_mass_g = mean(body_mass_g))

ggplot(penguins_by_sex, aes(x = species, y = body_mass_g, fill=sex)) +
  geom_col(position=position_dodge())
```

```{r}
penguins_by_year = penguins %>% 
  filter(!is.na(year)) %>% 
  group_by(species, year) %>% 
  summarise(body_mass_g = mean(body_mass_g))
  

ggplot(penguins_by_year, aes(x=year, y=body_mass_g, color=species)) +
  geom_line() +
  geom_point()
```

```{r}
fit = lm(body_mass_g ~ species * sex,
         data=penguins)

summary(fit)
```

```{r}
plot(residuals(fit))
```


```{r}
fit2 = lm(body_mass_g ~ species * sex + bill_length_mm + bill_depth_mm + flipper_length_mm,
         data=penguins)

summary(fit2)
```

```{r}
colnames(penguins)
```

```{r}
penguins_no_gentoo = penguins %>% 
  filter(species != "Gentoo")
```

```{r}
logistic_fit = glm(species ~ sex * body_mass_g,
                   data=penguins_no_gentoo, family = 'binomial')

summary(logistic_fit)
```

```{r}
preds = predict(logistic_fit, type='response')

penguins_no_gentoo_w_preds = cbind(penguins_no_gentoo, preds)
```

```{r}
logistic_fit2 = glm(species ~ sex * body_mass_g + bill_length_mm + bill_depth_mm + flipper_length_mm,
                    data=penguins_no_gentoo, family = 'binomial')

summary(logistic_fit2)
```

```{r}
preds2 = predict(logistic_fit2, type='response')

penguins_no_gentoo_w_preds2 = cbind(penguins_no_gentoo, preds2)
```

